### ISSUE TITLE
Add option to manage ruleset of local firewall

### ISSUE THREAD

**Issue by andreashaerter** [foundata/ansible-collection-sshd#2]
`run_sshd_manage_firewall: true|false`

**Comment by andreashaerter** [comment]
I think this addition definitely needs some discussion. While the idea of managing the firewall directly from within the role might seem convenient, it introduces several potential downsides:

- It can conflict with other tools or roles already handling firewall configuration.
- In practice, I doubt many users would feel comfortable enabling something like `run_sshd_manage_firewall: true`, effectively delegating firewall management to a role meant for SSH setup.
  
A more flexible and transparent approach would be to keep the role focused solely on configuring SSHD, and instead provide clear documentation on how to open the necessary ports manually if needed. For example:

1. Use this role to configure `sshd`
2. Then apply your own firewall rules, e.g.:
   ```yaml
   - name: Allow SSH through the firewall
     ansible.builtin.firewalld:
       port: 22/tcp
       permanent: true
       state: enabled
   ```

This keeps responsibilities well-scoped and avoids unwanted interference with broader system configuration.
